# Generated by Django 3.1.1 on 2020-11-03 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockattribute', models.CharField(max_length=20)),
                ('stockname', models.CharField(max_length=100)),
                ('stockprice', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tradereq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], default='buy', max_length=10)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('declined', 'declined'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='pending', max_length=50)),
                ('stock', models.CharField(choices=[('JPM', 'JPM'), ('ATT', 'ATT'), ('NFLX', 'NFLX'), ('AMZN', 'AMZN'), ('PFE', 'PFE'), ('MRNA', 'MRNA'), ('NKE', 'NKE'), ('META', 'META'), ('ADBE', 'ADBE'), ('PYPL', 'PYPL'), ('BA', 'BA'), ('SBUX', 'SBUX'), ('APL', 'APL'), ('TSLA', 'TSLA'), ('GOOGL', 'GOOGL')], max_length=100)),
                ('numberofstocks', models.IntegerField(default=0)),
                ('priceperstock', models.FloatField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_trade_inter', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_trade_inter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(choices=[('JPM', 'JPM'), ('ATT', 'ATT'), ('NFLX', 'NFLX'), ('AMZN', 'AMZN'), ('PFE', 'PFE'), ('MRNA', 'MRNA'), ('NKE', 'NKE'), ('META', 'META'), ('ADBE', 'ADBE'), ('PYPL', 'PYPL'), ('BA', 'BA'), ('SBUX', 'SBUX'), ('APL', 'APL'), ('TSLA', 'TSLA'), ('GOOGL', 'GOOGL')], max_length=100)),
                ('numberofstocks', models.IntegerField(default=0)),
                ('priceperstock', models.FloatField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_of_stock_international', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_of_stock_international', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userbalance', models.FloatField(default=1000000.0)),
                ('JPM', models.IntegerField(default=0)),
                ('ATT', models.IntegerField(default=0)),
                ('NFLX', models.IntegerField(default=0)),
                ('AMZN', models.IntegerField(default=0)),
                ('PFE', models.IntegerField(default=0)),
                ('MRNA', models.IntegerField(default=0)),
                ('NKE', models.IntegerField(default=0)),
                ('META', models.IntegerField(default=0)),
                ('ADBE', models.IntegerField(default=0)),
                ('PYPL', models.IntegerField(default=0)),
                ('BA', models.IntegerField(default=0)),
                ('SBUX', models.IntegerField(default=0)),
                ('APL', models.IntegerField(default=0)),
                ('TSLA', models.IntegerField(default=0)),
                ('GOOGL', models.IntegerField(default=0)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting', models.CharField(max_length=100)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_inter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
