# Generated by Django 3.1.1 on 2020-11-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0004_auto_20201106_0536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggedInUserInternational',
        ),
    ]
