# Generated by Django 3.1.1 on 2020-11-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0006_auto_20201106_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='priceperstock',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
