# Generated by Django 3.1.1 on 2020-11-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0008_auto_20201107_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='priceperstock',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
