# Generated by Django 3.1.1 on 2021-12-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0010_auto_20201107_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='GM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='GS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='KO',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='TGT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='TMUS',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stock',
            field=models.CharField(choices=[('JPM', 'JPM'), ('ATT', 'ATT'), ('NFLX', 'NFLX'), ('AMZN', 'AMZN'), ('PFE', 'PFE'), ('MRNA', 'MRNA'), ('NKE', 'NKE'), ('META', 'META'), ('ADBE', 'ADBE'), ('PYPL', 'PYPL'), ('BA', 'BA'), ('SBUX', 'SBUX'), ('APL', 'APL'), ('TSLA', 'TSLA'), ('GOOGL', 'GOOGL'), ('TMUS', 'TMUS'), ('GS', 'GS'), ('GM', 'GM'), ('KO', 'KO'), ('TGT', 'TGT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tradereq',
            name='stock',
            field=models.CharField(choices=[('JPM', 'JPM'), ('ATT', 'ATT'), ('NFLX', 'NFLX'), ('AMZN', 'AMZN'), ('PFE', 'PFE'), ('MRNA', 'MRNA'), ('NKE', 'NKE'), ('META', 'META'), ('ADBE', 'ADBE'), ('PYPL', 'PYPL'), ('BA', 'BA'), ('SBUX', 'SBUX'), ('APL', 'APL'), ('TSLA', 'TSLA'), ('GOOGL', 'GOOGL'), ('TMUS', 'TMUS'), ('GS', 'GS'), ('GM', 'GM'), ('KO', 'KO'), ('TGT', 'TGT')], max_length=100),
        ),
    ]
