# Generated by Django 3.1.1 on 2020-11-03 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockattribute', models.CharField(default='STOCK', max_length=20)),
                ('stockname', models.CharField(max_length=100)),
                ('stockprice', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tradereq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], default='buy', max_length=10)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('declined', 'declined'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='pending', max_length=50)),
                ('stock', models.CharField(choices=[('RBLBANK', 'RBLBANK'), ('MARUTI', 'MARUTI'), ('ADANIENT', 'ADANIENT'), ('TATASTEEL', 'TATASTEEL'), ('BOSCHLTD', 'BOSCHLTD'), ('RELIANCE', 'RELIANCE'), ('INFOSYS', 'INFOSYS'), ('BHARTIARTL', 'BHARTIARTL'), ('ITC', 'ITC'), ('HDFCBANK', 'HDFCBANK'), ('CIPLA', 'CIPLA'), ('TCS', 'TCS'), ('TATAMOTORS', 'TATAMOTORS'), ('ASIANPAINT', 'ASIANPAINT'), ('ICICIBANK', 'ICICIBANK')], max_length=100)),
                ('numberofstocks', models.IntegerField(default=0)),
                ('priceperstock', models.FloatField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_trade', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_trade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(choices=[('RBLBANK', 'RBLBANK'), ('MARUTI', 'MARUTI'), ('ADANIENT', 'ADANIENT'), ('TATASTEEL', 'TATASTEEL'), ('BOSCHLTD', 'BOSCHLTD'), ('RELIANCE', 'RELIANCE'), ('INFOSYS', 'INFOSYS'), ('BHARTIARTL', 'BHARTIARTL'), ('ITC', 'ITC'), ('HDFCBANK', 'HDFCBANK'), ('CIPLA', 'CIPLA'), ('TCS', 'TCS'), ('TATAMOTORS', 'TATAMOTORS'), ('ASIANPAINT', 'ASIANPAINT'), ('ICICIBANK', 'ICICIBANK')], max_length=100)),
                ('numberofstocks', models.IntegerField(default=0)),
                ('priceperstock', models.FloatField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_of_stock', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RBLBANK', models.IntegerField(default=0)),
                ('MARUTI', models.IntegerField(default=0)),
                ('ADANIENT', models.IntegerField(default=0)),
                ('TATASTEEL', models.IntegerField(default=0)),
                ('BOSCHLTD', models.IntegerField(default=0)),
                ('RELIANCE', models.IntegerField(default=0)),
                ('INFOSYS', models.IntegerField(default=0)),
                ('BHARTIARTL', models.IntegerField(default=0)),
                ('ITC', models.IntegerField(default=0)),
                ('HDFCBANK', models.IntegerField(default=0)),
                ('CIPLA', models.IntegerField(default=0)),
                ('TCS', models.IntegerField(default=0)),
                ('TATAMOTORS', models.IntegerField(default=0)),
                ('ASIANPAINT', models.IntegerField(default=0)),
                ('ICICIBANK', models.IntegerField(default=0)),
                ('userbalance', models.FloatField(default=1000000.0)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting', models.CharField(max_length=100)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
