# Generated by Django 3.1.1 on 2021-12-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201107_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='GLENMARK',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='HINDUNILVR',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='LUPIN',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='NETWORK18',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='ONGC',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stock',
            field=models.CharField(choices=[('RBLBANK', 'RBLBANK'), ('MARUTI', 'MARUTI'), ('ADANIENT', 'ADANIENT'), ('TATASTEEL', 'TATASTEEL'), ('BOSCHLTD', 'BOSCHLTD'), ('RELIANCE', 'RELIANCE'), ('INFOSYS', 'INFOSYS'), ('BHARTIARTL', 'BHARTIARTL'), ('ITC', 'ITC'), ('HDFCBANK', 'HDFCBANK'), ('CIPLA', 'CIPLA'), ('TCS', 'TCS'), ('TATAMOTORS', 'TATAMOTORS'), ('ASIANPAINT', 'ASIANPAINT'), ('ICICIBANK', 'ICICIBANK'), ('HINDUNILVR', 'HINDUNILVR'), ('GLENMARK', 'GLENMARK'), ('LUPIN', 'LUPIN'), ('ONGC', 'ONGC'), ('NETWORK18', 'NETWORK18')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tradereq',
            name='stock',
            field=models.CharField(choices=[('RBLBANK', 'RBLBANK'), ('MARUTI', 'MARUTI'), ('ADANIENT', 'ADANIENT'), ('TATASTEEL', 'TATASTEEL'), ('BOSCHLTD', 'BOSCHLTD'), ('RELIANCE', 'RELIANCE'), ('INFOSYS', 'INFOSYS'), ('BHARTIARTL', 'BHARTIARTL'), ('ITC', 'ITC'), ('HDFCBANK', 'HDFCBANK'), ('CIPLA', 'CIPLA'), ('TCS', 'TCS'), ('TATAMOTORS', 'TATAMOTORS'), ('ASIANPAINT', 'ASIANPAINT'), ('ICICIBANK', 'ICICIBANK'), ('HINDUNILVR', 'HINDUNILVR'), ('GLENMARK', 'GLENMARK'), ('LUPIN', 'LUPIN'), ('ONGC', 'ONGC'), ('NETWORK18', 'NETWORK18')], max_length=100),
        ),
    ]
